# Generated by Django 2.2.7 on 2020-02-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdata',
            name='lattitude',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='longitude',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='uid',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
